-- Create tables
create table public.profiles (
  id uuid references auth.users not null primary key,
  username text,
  avatar_url text,
  weight_kg numeric,
  activity_level text check (activity_level in ('sedentary', 'active', 'heroic')),
  daily_water_goal_ml int default 2000,
  mission text check (mission in ('stone_smasher', 'hydration_hero', 'skin_glow')),
  onboarding_complete boolean default false,
  xp int default 0
);

create table public.hydration_logs (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  amount_ml int not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create table public.medications (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  name text not null,
  dosage text,
  schedule_time time not null, -- '14:00:00'
  type text check (type in ('pill', 'liquid')) default 'pill'
);

create table public.medication_logs (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  medication_id bigint references public.medications not null,
  taken_at_date date default current_date not null,
  status text check (status in ('taken', 'skipped')) default 'taken',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS (Row Level Security)
alter table public.profiles enable row level security;
alter table public.hydration_logs enable row level security;
alter table public.medications enable row level security;
alter table public.medication_logs enable row level security;

-- Policies
create policy "Users can view own profile" on profiles for select using (auth.uid() = id);
create policy "Users can update own profile" on profiles for update using (auth.uid() = id);

create policy "Users can view own hydration" on hydration_logs for select using (auth.uid() = user_id);
create policy "Users can insert own hydration" on hydration_logs for insert with check (auth.uid() = user_id);

create policy "Users can view own medications" on medications for select using (auth.uid() = user_id);
create policy "Users can insert own medications" on medications for insert with check (auth.uid() = user_id);

create policy "Users can view own med logs" on medication_logs for select using (auth.uid() = user_id);
create policy "Users can insert own med logs" on medication_logs for insert with check (auth.uid() = user_id);

-- Trigger to handle new user signup (auto-create profile)
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, username, avatar_url)
  values (new.id, new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'avatar_url');
  return new;
end;
$$ language plpgsql security definer;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- Migration: Add onboarding columns to existing profiles table
-- Run these if the profiles table already exists:
-- alter table public.profiles add column if not exists weight_kg numeric;
-- alter table public.profiles add column if not exists activity_level text check (activity_level in ('sedentary', 'active', 'heroic'));
-- alter table public.profiles add column if not exists daily_water_goal_ml int default 2000;
-- alter table public.profiles add column if not exists mission text check (mission in ('stone_smasher', 'hydration_hero', 'skin_glow'));
-- Add XP to profiles if not exists
-- alter table public.profiles add column if not exists xp int default 0;

create table if not exists public.urine_logs (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  color_scale int check (color_scale between 1 and 8),
  volume text check (volume in ('small', 'medium', 'large')),
  notes text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.urine_logs enable row level security;

create policy "Users can view own urine logs" on public.urine_logs
  for select using (auth.uid() = user_id);

create policy "Users can insert own urine logs" on public.urine_logs
  for insert with check (auth.uid() = user_id);

-- Urine Achievements
create table if not exists public.urine_achievements (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  achievement_key text not null,
  unlocked_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(user_id, achievement_key)
);

alter table public.urine_achievements enable row level security;

create policy "Users can view own achievements" on public.urine_achievements
  for select using (auth.uid() = user_id);

create policy "Users can insert own achievements" on public.urine_achievements
  for insert with check (auth.uid() = user_id);

-- Missing RLS Policy for Deleting Medications
create policy "Users can delete own medications" on medications for delete using (auth.uid() = user_id);

-- Performance Indexes
create index if not exists idx_hydration_user_date on hydration_logs(user_id, created_at);
create index if not exists idx_medlogs_user_date on medication_logs(user_id, taken_at_date);
create index if not exists idx_meds_user on medications(user_id);
create index if not exists idx_urine_user_date on urine_logs(user_id, created_at);
create index if not exists idx_urine_achievements_user on urine_achievements(user_id);

-- Migration: Update urine_logs for 8-point scale (run if table already exists):
-- ALTER TABLE public.urine_logs DROP CONSTRAINT IF EXISTS urine_logs_color_scale_check;
-- ALTER TABLE public.urine_logs ADD CONSTRAINT urine_logs_color_scale_check CHECK (color_scale BETWEEN 1 AND 8);
-- ALTER TABLE public.urine_logs ADD COLUMN IF NOT EXISTS volume text CHECK (volume IN ('small', 'medium', 'large'));
-- ALTER TABLE public.urine_logs ADD COLUMN IF NOT EXISTS notes text;

-- Streak Calculation Function
create or replace function get_current_streak(user_uuid uuid)
returns integer
language plpgsql
security definer
as $$
declare
  streak_val integer;
begin
  -- Calculate consecutive days with logs ending today or yesterday
  with daily_logs as (
    select distinct date(created_at) as log_date
    from hydration_logs
    where user_id = user_uuid
  ),
  groups as (
      select
          log_date,
          log_date - cast(row_number() over (order by log_date) * interval '1 day' as date) as grp
      from daily_logs
  )
  select count(*) into streak_val
  from groups
  where grp = (
      select grp
      from groups
      where log_date >= current_date - 1
      order by log_date desc
      limit 1
  );

  return coalesce(streak_val, 0);
end;
$$;


-- Push Notification Subscriptions
create table if not exists public.push_subscriptions (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references auth.users not null,
  endpoint text not null,
  auth text not null,
  p256dh text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.push_subscriptions enable row level security;

create policy "Users can view own subscriptions" on public.push_subscriptions
  for select using (auth.uid() = user_id);

create policy "Users can insert own subscriptions" on public.push_subscriptions
  for insert with check (auth.uid() = user_id);

create policy "Users can delete own subscriptions" on public.push_subscriptions
  for delete using (auth.uid() = user_id);
